/**
 * Task API 테스트
 *
 * @generated by generate-tests skill
 * @see specs/test-be.md
 */

import request from 'supertest';
import app from '../src/app';

describe('Task API', () => {
  let createdTaskId: string;

  // POST /api/v1/tasks
  describe('POST /api/v1/tasks', () => {
    it('TC-001: 정상적인 Task 생성 (title만)', async () => {
      const res = await request(app)
        .post('/api/v1/tasks')
        .send({ title: 'Test Task' });

      expect(res.status).toBe(201);
      expect(res.body).toHaveProperty('id');
      expect(res.body.title).toBe('Test Task');
      expect(res.body.status).toBe('todo');
      expect(res.body.priority).toBe('medium');

      createdTaskId = res.body.id;
    });

    it('TC-002: 정상적인 Task 생성 (전체 필드)', async () => {
      const res = await request(app)
        .post('/api/v1/tasks')
        .send({
          title: 'Full Task',
          description: 'Description here',
          priority: 'high',
        });

      expect(res.status).toBe(201);
      expect(res.body.description).toBe('Description here');
      expect(res.body.priority).toBe('high');
    });

    it('TC-003: title 누락 시 400 에러', async () => {
      const res = await request(app)
        .post('/api/v1/tasks')
        .send({});

      expect(res.status).toBe(400);
      expect(res.body.code).toBe('INVALID_TITLE');
    });

    it('TC-004: title 빈 문자열 시 400 에러', async () => {
      const res = await request(app)
        .post('/api/v1/tasks')
        .send({ title: '' });

      expect(res.status).toBe(400);
      expect(res.body.code).toBe('INVALID_TITLE');
    });

    it('TC-005: title 공백만 있을 시 400 에러', async () => {
      const res = await request(app)
        .post('/api/v1/tasks')
        .send({ title: '   ' });

      expect(res.status).toBe(400);
      expect(res.body.code).toBe('INVALID_TITLE');
    });

    it('TC-006: title 100자 초과 시 400 에러', async () => {
      const res = await request(app)
        .post('/api/v1/tasks')
        .send({ title: 'a'.repeat(101) });

      expect(res.status).toBe(400);
      expect(res.body.code).toBe('INVALID_TITLE');
    });

    it('TC-007: priority 무효값 시 400 에러', async () => {
      const res = await request(app)
        .post('/api/v1/tasks')
        .send({ title: 'Test', priority: 'invalid' });

      expect(res.status).toBe(400);
      expect(res.body.code).toBe('INVALID_PRIORITY');
    });
  });

  // GET /api/v1/tasks
  describe('GET /api/v1/tasks', () => {
    it('TC-101: 전체 목록 조회', async () => {
      const res = await request(app).get('/api/v1/tasks');

      expect(res.status).toBe(200);
      expect(res.body).toHaveProperty('items');
      expect(res.body).toHaveProperty('total');
      expect(res.body).toHaveProperty('limit');
      expect(res.body).toHaveProperty('offset');
    });

    it('TC-102: status 필터링', async () => {
      const res = await request(app)
        .get('/api/v1/tasks')
        .query({ status: 'todo' });

      expect(res.status).toBe(200);
      res.body.items.forEach((task: any) => {
        expect(task.status).toBe('todo');
      });
    });

    it('TC-103: priority 필터링', async () => {
      const res = await request(app)
        .get('/api/v1/tasks')
        .query({ priority: 'high' });

      expect(res.status).toBe(200);
      res.body.items.forEach((task: any) => {
        expect(task.priority).toBe('high');
      });
    });

    it('TC-104: 페이지네이션', async () => {
      const res = await request(app)
        .get('/api/v1/tasks')
        .query({ limit: 10, offset: 0 });

      expect(res.status).toBe(200);
      expect(res.body.items.length).toBeLessThanOrEqual(10);
      expect(res.body.limit).toBe(10);
      expect(res.body.offset).toBe(0);
    });
  });

  // GET /api/v1/tasks/:id
  describe('GET /api/v1/tasks/:id', () => {
    it('TC-201: 존재하는 Task 조회', async () => {
      const res = await request(app).get(`/api/v1/tasks/${createdTaskId}`);

      expect(res.status).toBe(200);
      expect(res.body.id).toBe(createdTaskId);
    });

    it('TC-202: 존재하지 않는 Task 조회 시 404', async () => {
      const res = await request(app).get('/api/v1/tasks/non-existent-id');

      expect(res.status).toBe(404);
      expect(res.body.code).toBe('NOT_FOUND');
    });
  });

  // PATCH /api/v1/tasks/:id
  describe('PATCH /api/v1/tasks/:id', () => {
    it('TC-301: title 수정', async () => {
      const res = await request(app)
        .patch(`/api/v1/tasks/${createdTaskId}`)
        .send({ title: 'Updated Title' });

      expect(res.status).toBe(200);
      expect(res.body.title).toBe('Updated Title');
    });

    it('TC-302: status 변경', async () => {
      const res = await request(app)
        .patch(`/api/v1/tasks/${createdTaskId}`)
        .send({ status: 'done' });

      expect(res.status).toBe(200);
      expect(res.body.status).toBe('done');
    });

    it('TC-303: 존재하지 않는 Task 수정 시 404', async () => {
      const res = await request(app)
        .patch('/api/v1/tasks/non-existent-id')
        .send({ title: 'New' });

      expect(res.status).toBe(404);
      expect(res.body.code).toBe('NOT_FOUND');
    });

    it('TC-304: 무효 status 시 400', async () => {
      const res = await request(app)
        .patch(`/api/v1/tasks/${createdTaskId}`)
        .send({ status: 'invalid' });

      expect(res.status).toBe(400);
      expect(res.body.code).toBe('INVALID_STATUS');
    });
  });

  // DELETE /api/v1/tasks/:id
  describe('DELETE /api/v1/tasks/:id', () => {
    it('TC-401: 정상 삭제', async () => {
      const res = await request(app).delete(`/api/v1/tasks/${createdTaskId}`);

      expect(res.status).toBe(204);
    });

    it('TC-402: 존재하지 않는 Task 삭제 시 404', async () => {
      const res = await request(app).delete('/api/v1/tasks/non-existent-id');

      expect(res.status).toBe(404);
      expect(res.body.code).toBe('NOT_FOUND');
    });
  });
});
