/**
 * Task 컨트롤러
 *
 * @generated by scaffold-endpoint skill
 * @see specs/new_api_endpoint.md
 */

import { Request, Response, NextFunction } from 'express';
import { taskService } from '../services/task.service';
import { CreateTaskDto, UpdateTaskDto, TaskListQuery } from '../types/task';

export class TaskController {
  async create(req: Request, res: Response, next: NextFunction) {
    try {
      const dto: CreateTaskDto = req.body;

      // 입력 검증
      if (!dto.title || dto.title.trim() === '') {
        return res.status(400).json({ code: 'INVALID_TITLE', message: 'title is required' });
      }
      if (dto.title.length > 100) {
        return res.status(400).json({ code: 'INVALID_TITLE', message: 'title must be 100 characters or less' });
      }
      if (dto.priority && !['low', 'medium', 'high'].includes(dto.priority)) {
        return res.status(400).json({ code: 'INVALID_PRIORITY', message: 'priority must be low, medium, or high' });
      }

      const task = await taskService.create(dto);
      res.status(201).json(task);
    } catch (error) {
      next(error);
    }
  }

  async findAll(req: Request, res: Response, next: NextFunction) {
    try {
      const query: TaskListQuery = {
        status: req.query.status as any,
        priority: req.query.priority as any,
        limit: req.query.limit ? parseInt(req.query.limit as string) : undefined,
        offset: req.query.offset ? parseInt(req.query.offset as string) : undefined,
      };

      const result = await taskService.findAll(query);
      res.json(result);
    } catch (error) {
      next(error);
    }
  }

  async findById(req: Request, res: Response, next: NextFunction) {
    try {
      const task = await taskService.findById(req.params.id);
      if (!task) {
        return res.status(404).json({ code: 'NOT_FOUND', message: 'Task not found' });
      }
      res.json(task);
    } catch (error) {
      next(error);
    }
  }

  async update(req: Request, res: Response, next: NextFunction) {
    try {
      const dto: UpdateTaskDto = req.body;

      // 입력 검증
      if (dto.title !== undefined) {
        if (dto.title.trim() === '') {
          return res.status(400).json({ code: 'INVALID_TITLE', message: 'title cannot be empty' });
        }
        if (dto.title.length > 100) {
          return res.status(400).json({ code: 'INVALID_TITLE', message: 'title must be 100 characters or less' });
        }
      }
      if (dto.status && !['todo', 'in_progress', 'done'].includes(dto.status)) {
        return res.status(400).json({ code: 'INVALID_STATUS', message: 'status must be todo, in_progress, or done' });
      }

      const task = await taskService.update(req.params.id, dto);
      if (!task) {
        return res.status(404).json({ code: 'NOT_FOUND', message: 'Task not found' });
      }
      res.json(task);
    } catch (error) {
      next(error);
    }
  }

  async delete(req: Request, res: Response, next: NextFunction) {
    try {
      const deleted = await taskService.delete(req.params.id);
      if (!deleted) {
        return res.status(404).json({ code: 'NOT_FOUND', message: 'Task not found' });
      }
      res.status(204).send();
    } catch (error) {
      next(error);
    }
  }
}

export const taskController = new TaskController();
