<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConcurrencyPattern.Core\ConcurrencyPattern.Core.csproj" />
    <ProjectReference Include="..\ConcurrencyPattern.Infrastructure\ConcurrencyPattern.Infrastructure.csproj" />
    <ProjectReference Include="..\ConcurrencyPattern.Infrastructure.Redis\ConcurrencyPattern.Infrastructure.Redis.csproj" />
    <ProjectReference Include="..\ConcurrencyPattern.SequentialProcessor\ConcurrencyPattern.SequentialProcessor.csproj" />
    <ProjectReference Include="..\ConcurrencyPattern.Mediator\ConcurrencyPattern.Mediator.csproj" />
  </ItemGroup>

</Project>
