/**
 * Express 앱 설정
 *
 * @generated by scaffold-endpoint skill
 */

import express from 'express';
import taskRoutes from './routes/task.routes';

const app = express();

// 미들웨어
app.use(express.json());

// 라우트
app.use('/api/v1/tasks', taskRoutes);

// 에러 핸들러
app.use((err: Error, req: express.Request, res: express.Response, next: express.NextFunction) => {
  console.error(err);
  res.status(500).json({ code: 'INTERNAL_ERROR', message: 'Internal server error' });
});

export default app;
