/**
 * Task 타입 정의
 *
 * @generated by scaffold-endpoint skill
 * @see specs/new_api_endpoint.md
 */

export interface Task {
  id: string;
  title: string;
  description: string | null;
  priority: Priority;
  status: Status;
  createdAt: Date;
  updatedAt: Date;
}

export type Priority = 'low' | 'medium' | 'high';
export type Status = 'todo' | 'in_progress' | 'done';

export interface CreateTaskDto {
  title: string;
  description?: string;
  priority?: Priority;
}

export interface UpdateTaskDto {
  title?: string;
  description?: string;
  priority?: Priority;
  status?: Status;
}

export interface TaskListQuery {
  status?: Status;
  priority?: Priority;
  limit?: number;
  offset?: number;
}

export interface TaskListResponse {
  items: Task[];
  total: number;
  limit: number;
  offset: number;
}
