/**
 * Task 라우트
 *
 * @generated by scaffold-endpoint skill
 * @see specs/new_api_endpoint.md
 */

import { Router } from 'express';
import { taskController } from '../controllers/task.controller';

const router = Router();

// POST /api/v1/tasks - Task 생성
router.post('/', (req, res, next) => taskController.create(req, res, next));

// GET /api/v1/tasks - Task 목록 조회
router.get('/', (req, res, next) => taskController.findAll(req, res, next));

// GET /api/v1/tasks/:id - Task 단건 조회
router.get('/:id', (req, res, next) => taskController.findById(req, res, next));

// PATCH /api/v1/tasks/:id - Task 수정
router.patch('/:id', (req, res, next) => taskController.update(req, res, next));

// DELETE /api/v1/tasks/:id - Task 삭제
router.delete('/:id', (req, res, next) => taskController.delete(req, res, next));

export default router;
