/**
 * Task 서비스
 *
 * @generated by scaffold-endpoint skill
 * @see specs/new_api_endpoint.md
 */

import { v4 as uuidv4 } from 'uuid';
import {
  Task,
  CreateTaskDto,
  UpdateTaskDto,
  TaskListQuery,
  TaskListResponse,
} from '../types/task';

// In-memory storage (TODO: 실제 DB로 교체)
const tasks: Map<string, Task> = new Map();

export class TaskService {
  async create(dto: CreateTaskDto): Promise<Task> {
    const now = new Date();
    const task: Task = {
      id: uuidv4(),
      title: dto.title,
      description: dto.description ?? null,
      priority: dto.priority ?? 'medium',
      status: 'todo',
      createdAt: now,
      updatedAt: now,
    };

    tasks.set(task.id, task);
    return task;
  }

  async findAll(query: TaskListQuery): Promise<TaskListResponse> {
    let items = Array.from(tasks.values());

    // 필터링
    if (query.status) {
      items = items.filter((t) => t.status === query.status);
    }
    if (query.priority) {
      items = items.filter((t) => t.priority === query.priority);
    }

    const total = items.length;

    // 페이지네이션
    const limit = query.limit ?? 20;
    const offset = query.offset ?? 0;
    items = items.slice(offset, offset + limit);

    return { items, total, limit, offset };
  }

  async findById(id: string): Promise<Task | null> {
    return tasks.get(id) ?? null;
  }

  async update(id: string, dto: UpdateTaskDto): Promise<Task | null> {
    const task = tasks.get(id);
    if (!task) {
      return null;
    }

    const updated: Task = {
      ...task,
      title: dto.title ?? task.title,
      description: dto.description ?? task.description,
      priority: dto.priority ?? task.priority,
      status: dto.status ?? task.status,
      updatedAt: new Date(),
    };

    tasks.set(id, updated);
    return updated;
  }

  async delete(id: string): Promise<boolean> {
    return tasks.delete(id);
  }
}

export const taskService = new TaskService();
